version: '3'

services:
  gcb-postprocessor:
      container_name: gcb-postprocessor
      build: .
      environment:
        - AUTH_TOKEN=${AUTH_TOKEN}
        - PORT=3432
        - NODE_ENV=%%NODE_ENV%%
        - POST_PROCESSOR_METHOD_FILE_SOURCE=${POST_PROCESSOR_METHOD_FILE_SOURCE}
      ports:
        - "0.0.0.0:3432:3432"
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "20"
      #    volumes:
      #      - ./:/var/app
      restart: always

networks:
  default:
    external:
      name: skynet
