name: Deploy buy runner

on:
  push:
    branches: [ "master" ]

jobs:
  prepare-environment:
    runs-on: self-hosted
    # needs: test
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Remove unused data
        run: docker stop gcb-postprocessor && docker rm gcb-postprocessor
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker-compose up -d
