name: Deploy release

env:
  POST_PROCESSOR_METHOD_FILE_SOURCE: /home/deployer/web/post-processor.method2.ts

on:
  push:
    branches: [ "release" ]

jobs:  
  test:
    runs-on: prod
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
  prepare-environment:
    runs-on: prod
    needs: test
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down ;
      - name: Remove unused data
        run: /bin/bash -c "/usr/bin/docker stop gcb-postprocessor ; /usr/bin/docker rm gcb-postprocessor; /usr/bin/docker image rm gcb-postprocessor-gcb-postprocessor; " || true
  deploy:
    runs-on: prod
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: pwd
        run: pwd
      - name: ll
        run: ls -la
      - name: copy postprocessor
        run: cp ${POST_PROCESSOR_METHOD_FILE_SOURCE} ./src/modules/post-processor/post-processor-real.method.ts
      - name: docker compose
        run: docker compose up -d
